
var data = [{
    "id": 1,
    "first_name": "Chadwick",
    "last_name": "Deverille",
    "email": "cdeverille0@pbs.org",
    "gender": "Male",
    "ip_address": "15.217.141.79",
    "empresa": 1,
    "fecha": "07/11/2017"
}, {
    "id": 2,
    "first_name": "Griffy",
    "last_name": "Graal",
    "email": "ggraal1@samsung.com",
    "gender": "Male",
    "ip_address": "221.120.139.95",
    "empresa": 2,
    "fecha": "13/02/2018"
}, {
    "id": 3,
    "first_name": "Agata",
    "last_name": "Bolesworth",
    "email": "abolesworth2@dagondesign.com",
    "gender": "Female",
    "ip_address": "57.98.121.53",
    "empresa": 3,
    "fecha": "02/06/2018"
}, {
    "id": 4,
    "first_name": "Mike",
    "last_name": "Brecknell",
    "email": "mbrecknell3@blogtalkradio.com",
    "gender": "Male",
    "ip_address": "120.173.77.26",
    "empresa": 4,
    "fecha": "11/01/2018"
}, {
    "id": 5,
    "first_name": "Lorraine",
    "last_name": "Truin",
    "email": "ltruin4@bravesites.com",
    "gender": "Female",
    "ip_address": "106.98.37.253",
    "empresa": 5,
    "fecha": "30/04/2018"
}, {
    "id": 6,
    "first_name": "Rorie",
    "last_name": "Brazil",
    "email": "rbrazil5@gravatar.com",
    "gender": "Female",
    "ip_address": "140.207.42.75",
    "empresa": 6,
    "fecha": "22/06/2018"
}, {
    "id": 7,
    "first_name": "Ardisj",
    "last_name": "Miall",
    "email": "amiall6@dailymail.co.uk",
    "gender": "Female",
    "ip_address": "111.155.197.193",
    "empresa": 7,
    "fecha": "24/07/2017"
}, {
    "id": 8,
    "first_name": "Giraud",
    "last_name": "Kite",
    "email": "gkite7@ameblo.jp",
    "gender": "Male",
    "ip_address": "60.154.54.77",
    "empresa": 8,
    "fecha": "15/09/2017"
}, {
    "id": 9,
    "first_name": "Manny",
    "last_name": "Hasloch",
    "email": "mhasloch8@topsy.com",
    "gender": "Male",
    "ip_address": "170.254.158.157",
    "empresa": 9,
    "fecha": "11/11/2017"
}, {
    "id": 10,
    "first_name": "Nickie",
    "last_name": "Stannion",
    "email": "nstannion9@opensource.org",
    "gender": "Female",
    "ip_address": "19.235.108.75",
    "empresa": 10,
    "fecha": "08/12/2017"
}, {
    "id": 11,
    "first_name": "Berke",
    "last_name": "Sankey",
    "email": "bsankeya@vkontakte.ru",
    "gender": "Male",
    "ip_address": "164.200.252.97",
    "empresa": 11,
    "fecha": "26/05/2018"
}, {
    "id": 12,
    "first_name": "Donovan",
    "last_name": "Wisker",
    "email": "dwiskerb@sitemeter.com",
    "gender": "Male",
    "ip_address": "3.164.202.149",
    "empresa": 12,
    "fecha": "08/11/2017"
}, {
    "id": 13,
    "first_name": "Christoforo",
    "last_name": "Cleaves",
    "email": "ccleavesc@psu.edu",
    "gender": "Male",
    "ip_address": "121.180.41.3",
    "empresa": 13,
    "fecha": "06/09/2017"
}, {
    "id": 14,
    "first_name": "Lauralee",
    "last_name": "Reck",
    "email": "lreckd@goodreads.com",
    "gender": "Female",
    "ip_address": "115.160.207.100",
    "empresa": 14,
    "fecha": "21/02/2018"
}, {
    "id": 15,
    "first_name": "Rainer",
    "last_name": "Bowdler",
    "email": "rbowdlere@indiegogo.com",
    "gender": "Male",
    "ip_address": "122.252.175.213",
    "empresa": 15,
    "fecha": "25/08/2017"
}, {
    "id": 16,
    "first_name": "Fayth",
    "last_name": "Rosetti",
    "email": "frosettif@github.com",
    "gender": "Female",
    "ip_address": "34.232.88.52",
    "empresa": 16,
    "fecha": "25/11/2017"
}, {
    "id": 17,
    "first_name": "Nefen",
    "last_name": "Gotthard.sf",
    "email": "ngotthardsfg@paginegialle.it",
    "gender": "Male",
    "ip_address": "71.146.103.79",
    "empresa": 17,
    "fecha": "01/03/2018"
}, {
    "id": 18,
    "first_name": "Michal",
    "last_name": "Gerardi",
    "email": "mgerardih@eepurl.com",
    "gender": "Male",
    "ip_address": "220.110.105.54",
    "empresa": 18,
    "fecha": "05/11/2017"
}, {
    "id": 19,
    "first_name": "Dorolisa",
    "last_name": "Warboy",
    "email": "dwarboyi@cam.ac.uk",
    "gender": "Female",
    "ip_address": "48.207.196.35",
    "empresa": 19,
    "fecha": "25/06/2018"
}, {
    "id": 20,
    "first_name": "Dickie",
    "last_name": "Murty",
    "email": "dmurtyj@businessinsider.com",
    "gender": "Male",
    "ip_address": "225.79.207.220",
    "empresa": 20,
    "fecha": "04/04/2018"
}, {
    "id": 21,
    "first_name": "Leyla",
    "last_name": "Minithorpe",
    "email": "lminithorpek@people.com.cn",
    "gender": "Female",
    "ip_address": "93.49.38.186",
    "empresa": 21,
    "fecha": "29/03/2018"
}, {
    "id": 22,
    "first_name": "Emmerich",
    "last_name": "Dungey",
    "email": "edungeyl@skyrock.com",
    "gender": "Male",
    "ip_address": "67.173.17.131",
    "empresa": 22,
    "fecha": "26/10/2017"
}, {
    "id": 23,
    "first_name": "Hadlee",
    "last_name": "Triplet",
    "email": "htripletm@nydailynews.com",
    "gender": "Male",
    "ip_address": "220.159.163.129",
    "empresa": 23,
    "fecha": "09/07/2018"
}, {
    "id": 24,
    "first_name": "Eydie",
    "last_name": "Parlet",
    "email": "eparletn@hubpages.com",
    "gender": "Female",
    "ip_address": "195.112.168.185",
    "empresa": 24,
    "fecha": "16/06/2018"
}, {
    "id": 25,
    "first_name": "Gretna",
    "last_name": "Jurick",
    "email": "gjuricko@yellowbook.com",
    "gender": "Female",
    "ip_address": "240.241.176.47",
    "empresa": 25,
    "fecha": "03/07/2017"
}, {
    "id": 26,
    "first_name": "Odilia",
    "last_name": "Ferier",
    "email": "oferierp@hugedomains.com",
    "gender": "Female",
    "ip_address": "154.205.4.93",
    "empresa": 26,
    "fecha": "24/06/2018"
}, {
    "id": 27,
    "first_name": "Lin",
    "last_name": "Leavens",
    "email": "lleavensq@fotki.com",
    "gender": "Female",
    "ip_address": "7.204.132.252",
    "empresa": 27,
    "fecha": "15/07/2017"
}, {
    "id": 28,
    "first_name": "Antonina",
    "last_name": "Batters",
    "email": "abattersr@yolasite.com",
    "gender": "Female",
    "ip_address": "248.131.241.106",
    "empresa": 28,
    "fecha": "22/01/2018"
}, {
    "id": 29,
    "first_name": "Maxie",
    "last_name": "Beneteau",
    "email": "mbeneteaus@desdev.cn",
    "gender": "Female",
    "ip_address": "42.68.48.172",
    "empresa": 29,
    "fecha": "24/11/2017"
}, {
    "id": 30,
    "first_name": "Trudi",
    "last_name": "Rickman",
    "email": "trickmant@seesaa.net",
    "gender": "Female",
    "ip_address": "153.196.188.170",
    "empresa": 30,
    "fecha": "16/06/2018"
}, {
    "id": 31,
    "first_name": "Reinold",
    "last_name": "Prigg",
    "email": "rpriggu@ezinearticles.com",
    "gender": "Male",
    "ip_address": "119.46.17.243",
    "empresa": 31,
    "fecha": "21/02/2018"
}, {
    "id": 32,
    "first_name": "Tab",
    "last_name": "Minchi",
    "email": "tminchiv@huffingtonpost.com",
    "gender": "Male",
    "ip_address": "142.214.82.101",
    "empresa": 32,
    "fecha": "24/03/2018"
}, {
    "id": 33,
    "first_name": "Barty",
    "last_name": "Poutress",
    "email": "bpoutressw@bravesites.com",
    "gender": "Male",
    "ip_address": "102.45.165.94",
    "empresa": 33,
    "fecha": "25/01/2018"
}, {
    "id": 34,
    "first_name": "Gauthier",
    "last_name": "Welfare",
    "email": "gwelfarex@spiegel.de",
    "gender": "Male",
    "ip_address": "36.46.225.135",
    "empresa": 34,
    "fecha": "20/07/2017"
}, {
    "id": 35,
    "first_name": "Puff",
    "last_name": "Pahler",
    "email": "ppahlery@vkontakte.ru",
    "gender": "Male",
    "ip_address": "131.193.199.73",
    "empresa": 35,
    "fecha": "05/11/2017"
}, {
    "id": 36,
    "first_name": "Crichton",
    "last_name": "Websdale",
    "email": "cwebsdalez@walmart.com",
    "gender": "Male",
    "ip_address": "139.47.210.90",
    "empresa": 36,
    "fecha": "15/01/2018"
}, {
    "id": 37,
    "first_name": "Heidi",
    "last_name": "Shawl",
    "email": "hshawl10@blogger.com",
    "gender": "Female",
    "ip_address": "255.42.128.136",
    "empresa": 37,
    "fecha": "15/06/2018"
}, {
    "id": 38,
    "first_name": "Stanford",
    "last_name": "Witty",
    "email": "switty11@prnewswire.com",
    "gender": "Male",
    "ip_address": "89.133.148.251",
    "empresa": 38,
    "fecha": "03/12/2017"
}, {
    "id": 39,
    "first_name": "Jackson",
    "last_name": "Shortland",
    "email": "jshortland12@ezinearticles.com",
    "gender": "Male",
    "ip_address": "126.159.203.4",
    "empresa": 39,
    "fecha": "06/03/2018"
}, {
    "id": 40,
    "first_name": "Aubry",
    "last_name": "Cavnor",
    "email": "acavnor13@github.com",
    "gender": "Female",
    "ip_address": "30.193.86.58",
    "empresa": 40,
    "fecha": "12/09/2017"
}, {
    "id": 41,
    "first_name": "Opal",
    "last_name": "Boylund",
    "email": "oboylund14@facebook.com",
    "gender": "Female",
    "ip_address": "198.161.133.135",
    "empresa": 41,
    "fecha": "18/11/2017"
}, {
    "id": 42,
    "first_name": "Marney",
    "last_name": "Budden",
    "email": "mbudden15@vk.com",
    "gender": "Female",
    "ip_address": "33.149.185.163",
    "empresa": 42,
    "fecha": "24/12/2017"
}, {
    "id": 43,
    "first_name": "Brantley",
    "last_name": "Dougal",
    "email": "bdougal16@unicef.org",
    "gender": "Male",
    "ip_address": "121.126.236.57",
    "empresa": 43,
    "fecha": "04/01/2018"
}, {
    "id": 44,
    "first_name": "Dunc",
    "last_name": "Camillo",
    "email": "dcamillo17@booking.com",
    "gender": "Male",
    "ip_address": "53.55.117.145",
    "empresa": 44,
    "fecha": "20/07/2017"
}, {
    "id": 45,
    "first_name": "Davida",
    "last_name": "Chaperlin",
    "email": "dchaperlin18@quantcast.com",
    "gender": "Female",
    "ip_address": "153.190.236.19",
    "empresa": 45,
    "fecha": "23/01/2018"
}, {
    "id": 46,
    "first_name": "Jammie",
    "last_name": "Cowdroy",
    "email": "jcowdroy19@mapy.cz",
    "gender": "Female",
    "ip_address": "216.229.213.242",
    "empresa": 46,
    "fecha": "20/12/2017"
}, {
    "id": 47,
    "first_name": "Tyne",
    "last_name": "Lorden",
    "email": "tlorden1a@businessweek.com",
    "gender": "Female",
    "ip_address": "204.1.146.135",
    "empresa": 47,
    "fecha": "01/07/2018"
}, {
    "id": 48,
    "first_name": "Palmer",
    "last_name": "Greenstock",
    "email": "pgreenstock1b@deviantart.com",
    "gender": "Male",
    "ip_address": "28.200.30.234",
    "empresa": 48,
    "fecha": "07/06/2018"
}, {
    "id": 49,
    "first_name": "Quincy",
    "last_name": "De Fries",
    "email": "qdefries1c@wix.com",
    "gender": "Male",
    "ip_address": "88.244.155.226",
    "empresa": 49,
    "fecha": "09/02/2018"
}, {
    "id": 50,
    "first_name": "Sarge",
    "last_name": "Boxill",
    "email": "sboxill1d@dedecms.com",
    "gender": "Male",
    "ip_address": "0.13.181.28",
    "empresa": 50,
    "fecha": "28/07/2017"
}, {
    "id": 51,
    "first_name": "Gussy",
    "last_name": "Cronin",
    "email": "gcronin1e@163.com",
    "gender": "Female",
    "ip_address": "184.122.47.123",
    "empresa": 51,
    "fecha": "16/04/2018"
}, {
    "id": 52,
    "first_name": "Constantin",
    "last_name": "Sydney",
    "email": "csydney1f@sakura.ne.jp",
    "gender": "Male",
    "ip_address": "211.95.146.188",
    "empresa": 52,
    "fecha": "12/05/2018"
}, {
    "id": 53,
    "first_name": "Iseabal",
    "last_name": "Grigs",
    "email": "igrigs1g@merriam-webster.com",
    "gender": "Female",
    "ip_address": "5.221.252.254",
    "empresa": 53,
    "fecha": "26/08/2017"
}, {
    "id": 54,
    "first_name": "Jaclyn",
    "last_name": "Di Bartolommeo",
    "email": "jdibartolommeo1h@springer.com",
    "gender": "Female",
    "ip_address": "221.31.143.164",
    "empresa": 54,
    "fecha": "04/05/2018"
}, {
    "id": 55,
    "first_name": "Isidor",
    "last_name": "Powderham",
    "email": "ipowderham1i@geocities.com",
    "gender": "Male",
    "ip_address": "163.187.151.93",
    "empresa": 55,
    "fecha": "20/05/2018"
}, {
    "id": 56,
    "first_name": "Felicio",
    "last_name": "Godwyn",
    "email": "fgodwyn1j@china.com.cn",
    "gender": "Male",
    "ip_address": "178.36.88.121",
    "empresa": 56,
    "fecha": "20/06/2018"
}, {
    "id": 57,
    "first_name": "Pavel",
    "last_name": "Lilion",
    "email": "plilion1k@twitter.com",
    "gender": "Male",
    "ip_address": "40.65.196.247",
    "empresa": 57,
    "fecha": "12/08/2017"
}, {
    "id": 58,
    "first_name": "Kin",
    "last_name": "Mara",
    "email": "kmara1l@engadget.com",
    "gender": "Male",
    "ip_address": "176.163.145.132",
    "empresa": 58,
    "fecha": "06/03/2018"
}, {
    "id": 59,
    "first_name": "Tommi",
    "last_name": "Ghost",
    "email": "tghost1m@wsj.com",
    "gender": "Female",
    "ip_address": "137.187.157.170",
    "empresa": 59,
    "fecha": "27/07/2017"
}, {
    "id": 60,
    "first_name": "Tadeas",
    "last_name": "Padkin",
    "email": "tpadkin1n@gnu.org",
    "gender": "Male",
    "ip_address": "254.116.26.94",
    "empresa": 60,
    "fecha": "08/10/2017"
}, {
    "id": 61,
    "first_name": "Adham",
    "last_name": "Fifoot",
    "email": "afifoot1o@psu.edu",
    "gender": "Male",
    "ip_address": "161.82.239.24",
    "empresa": 61,
    "fecha": "05/12/2017"
}, {
    "id": 62,
    "first_name": "Tabor",
    "last_name": "Fallows",
    "email": "tfallows1p@foxnews.com",
    "gender": "Male",
    "ip_address": "82.27.72.188",
    "empresa": 62,
    "fecha": "12/11/2017"
}, {
    "id": 63,
    "first_name": "Vikky",
    "last_name": "Searston",
    "email": "vsearston1q@google.de",
    "gender": "Female",
    "ip_address": "2.43.155.232",
    "empresa": 63,
    "fecha": "14/03/2018"
}, {
    "id": 64,
    "first_name": "Lianne",
    "last_name": "Wigin",
    "email": "lwigin1r@mayoclinic.com",
    "gender": "Female",
    "ip_address": "210.206.14.50",
    "empresa": 64,
    "fecha": "16/07/2018"
}, {
    "id": 65,
    "first_name": "Melisandra",
    "last_name": "Hoxey",
    "email": "mhoxey1s@bluehost.com",
    "gender": "Female",
    "ip_address": "90.144.150.13",
    "empresa": 65,
    "fecha": "12/05/2018"
}, {
    "id": 66,
    "first_name": "Lucien",
    "last_name": "Faireclough",
    "email": "lfaireclough1t@about.me",
    "gender": "Male",
    "ip_address": "190.129.128.204",
    "empresa": 66,
    "fecha": "08/05/2018"
}, {
    "id": 67,
    "first_name": "Bond",
    "last_name": "Wolfarth",
    "email": "bwolfarth1u@php.net",
    "gender": "Male",
    "ip_address": "193.240.168.45",
    "empresa": 67,
    "fecha": "14/12/2017"
}, {
    "id": 68,
    "first_name": "Latashia",
    "last_name": "Harler",
    "email": "lharler1v@shutterfly.com",
    "gender": "Female",
    "ip_address": "78.102.126.34",
    "empresa": 68,
    "fecha": "07/08/2017"
}, {
    "id": 69,
    "first_name": "Maisey",
    "last_name": "Decreuze",
    "email": "mdecreuze1w@posterous.com",
    "gender": "Female",
    "ip_address": "132.224.80.226",
    "empresa": 69,
    "fecha": "29/04/2018"
}, {
    "id": 70,
    "first_name": "Nickie",
    "last_name": "Meedendorpe",
    "email": "nmeedendorpe1x@sina.com.cn",
    "gender": "Female",
    "ip_address": "19.227.133.28",
    "empresa": 70,
    "fecha": "18/12/2017"
}, {
    "id": 71,
    "first_name": "Ruth",
    "last_name": "Dobrowolny",
    "email": "rdobrowolny1y@blogtalkradio.com",
    "gender": "Female",
    "ip_address": "27.129.241.234",
    "empresa": 71,
    "fecha": "08/07/2017"
}, {
    "id": 72,
    "first_name": "Karlotte",
    "last_name": "Spinas",
    "email": "kspinas1z@xrea.com",
    "gender": "Female",
    "ip_address": "101.172.223.221",
    "empresa": 72,
    "fecha": "13/09/2017"
}, {
    "id": 73,
    "first_name": "Zeb",
    "last_name": "Lytell",
    "email": "zlytell20@gravatar.com",
    "gender": "Male",
    "ip_address": "27.117.165.69",
    "empresa": 73,
    "fecha": "17/08/2017"
}, {
    "id": 74,
    "first_name": "Wilona",
    "last_name": "Kertess",
    "email": "wkertess21@miibeian.gov.cn",
    "gender": "Female",
    "ip_address": "13.82.36.107",
    "empresa": 74,
    "fecha": "16/07/2017"
}, {
    "id": 75,
    "first_name": "Kenon",
    "last_name": "McMorran",
    "email": "kmcmorran22@ning.com",
    "gender": "Male",
    "ip_address": "75.43.167.47",
    "empresa": 75,
    "fecha": "18/10/2017"
}, {
    "id": 76,
    "first_name": "Timi",
    "last_name": "Treweke",
    "email": "ttreweke23@microsoft.com",
    "gender": "Female",
    "ip_address": "255.229.187.6",
    "empresa": 76,
    "fecha": "21/11/2017"
}, {
    "id": 77,
    "first_name": "Gaylord",
    "last_name": "Bavester",
    "email": "gbavester24@walmart.com",
    "gender": "Male",
    "ip_address": "5.97.39.169",
    "empresa": 77,
    "fecha": "23/07/2017"
}, {
    "id": 78,
    "first_name": "Kerk",
    "last_name": "Caret",
    "email": "kcaret25@cnn.com",
    "gender": "Male",
    "ip_address": "218.9.33.79",
    "empresa": 78,
    "fecha": "02/11/2017"
}, {
    "id": 79,
    "first_name": "Kingsley",
    "last_name": "Arnull",
    "email": "karnull26@timesonline.co.uk",
    "gender": "Male",
    "ip_address": "183.72.25.132",
    "empresa": 79,
    "fecha": "25/11/2017"
}, {
    "id": 80,
    "first_name": "Cassondra",
    "last_name": "Kinsman",
    "email": "ckinsman27@ovh.net",
    "gender": "Female",
    "ip_address": "35.208.143.11",
    "empresa": 80,
    "fecha": "10/10/2017"
}, {
    "id": 81,
    "first_name": "Ignacius",
    "last_name": "Danby",
    "email": "idanby28@amazon.com",
    "gender": "Male",
    "ip_address": "178.142.230.64",
    "empresa": 81,
    "fecha": "25/04/2018"
}, {
    "id": 82,
    "first_name": "Fernande",
    "last_name": "Colebrook",
    "email": "fcolebrook29@friendfeed.com",
    "gender": "Female",
    "ip_address": "163.177.44.91",
    "empresa": 82,
    "fecha": "26/03/2018"
}, {
    "id": 83,
    "first_name": "Granville",
    "last_name": "Chatan",
    "email": "gchatan2a@ed.gov",
    "gender": "Male",
    "ip_address": "205.176.144.2",
    "empresa": 83,
    "fecha": "20/11/2017"
}, {
    "id": 84,
    "first_name": "Jasper",
    "last_name": "Blandamere",
    "email": "jblandamere2b@twitter.com",
    "gender": "Male",
    "ip_address": "168.58.5.166",
    "empresa": 84,
    "fecha": "07/11/2017"
}, {
    "id": 85,
    "first_name": "Rem",
    "last_name": "Allcock",
    "email": "rallcock2c@squidoo.com",
    "gender": "Male",
    "ip_address": "194.81.52.145",
    "empresa": 85,
    "fecha": "19/04/2018"
}, {
    "id": 86,
    "first_name": "Penrod",
    "last_name": "Dedam",
    "email": "pdedam2d@vimeo.com",
    "gender": "Male",
    "ip_address": "10.5.22.135",
    "empresa": 86,
    "fecha": "19/12/2017"
}, {
    "id": 87,
    "first_name": "Bibbye",
    "last_name": "Apperley",
    "email": "bapperley2e@vistaprint.com",
    "gender": "Female",
    "ip_address": "104.175.21.199",
    "empresa": 87,
    "fecha": "04/12/2017"
}, {
    "id": 88,
    "first_name": "Torrey",
    "last_name": "Doxsey",
    "email": "tdoxsey2f@domainmarket.com",
    "gender": "Male",
    "ip_address": "151.35.30.0",
    "empresa": 88,
    "fecha": "27/01/2018"
}, {
    "id": 89,
    "first_name": "Ignace",
    "last_name": "Robison",
    "email": "irobison2g@instagram.com",
    "gender": "Male",
    "ip_address": "104.233.212.186",
    "empresa": 89,
    "fecha": "20/08/2017"
}, {
    "id": 90,
    "first_name": "Gaylene",
    "last_name": "Pannett",
    "email": "gpannett2h@devhub.com",
    "gender": "Female",
    "ip_address": "127.174.16.213",
    "empresa": 90,
    "fecha": "11/07/2017"
}, {
    "id": 91,
    "first_name": "Twila",
    "last_name": "Gyde",
    "email": "tgyde2i@constantcontact.com",
    "gender": "Female",
    "ip_address": "234.218.232.168",
    "empresa": 91,
    "fecha": "09/07/2018"
}, {
    "id": 92,
    "first_name": "Renee",
    "last_name": "Backshaw",
    "email": "rbackshaw2j@earthlink.net",
    "gender": "Female",
    "ip_address": "47.156.90.254",
    "empresa": 92,
    "fecha": "17/03/2018"
}, {
    "id": 93,
    "first_name": "Rey",
    "last_name": "Swinnerton",
    "email": "rswinnerton2k@eepurl.com",
    "gender": "Female",
    "ip_address": "248.38.215.11",
    "empresa": 93,
    "fecha": "15/11/2017"
}, {
    "id": 94,
    "first_name": "Darrel",
    "last_name": "Wetherby",
    "email": "dwetherby2l@livejournal.com",
    "gender": "Male",
    "ip_address": "54.62.33.180",
    "empresa": 94,
    "fecha": "04/02/2018"
}, {
    "id": 95,
    "first_name": "Neall",
    "last_name": "Shedden",
    "email": "nshedden2m@spotify.com",
    "gender": "Male",
    "ip_address": "100.100.174.89",
    "empresa": 95,
    "fecha": "29/07/2017"
}, {
    "id": 96,
    "first_name": "Boonie",
    "last_name": "Petruska",
    "email": "bpetruska2n@upenn.edu",
    "gender": "Male",
    "ip_address": "127.121.126.75",
    "empresa": 96,
    "fecha": "10/08/2017"
}, {
    "id": 97,
    "first_name": "Maggi",
    "last_name": "McGerraghty",
    "email": "mmcgerraghty2o@arstechnica.com",
    "gender": "Female",
    "ip_address": "48.188.52.26",
    "empresa": 97,
    "fecha": "05/11/2017"
}, {
    "id": 98,
    "first_name": "Dode",
    "last_name": "Bottle",
    "email": "dbottle2p@amazon.de",
    "gender": "Female",
    "ip_address": "77.7.37.237",
    "empresa": 98,
    "fecha": "09/02/2018"
}, {
    "id": 99,
    "first_name": "Aura",
    "last_name": "Tersay",
    "email": "atersay2q@digg.com",
    "gender": "Female",
    "ip_address": "54.156.209.215",
    "empresa": 99,
    "fecha": "03/07/2018"
}, {
    "id": 100,
    "first_name": "Lanna",
    "last_name": "Perelli",
    "email": "lperelli2r@ftc.gov",
    "gender": "Female",
    "ip_address": "45.225.21.218",
    "empresa": 100,
    "fecha": "13/03/2018"
}]

var init = function () {
    $('#table').bootstrapTable({

        data: data,
        cache: false,
        height: 494,
        striped: false,
        pagination: true,
        sortable: true,
        locale: 'es-Ar',
        sortable: true,
        sortOrder: 'asc',
        showToggle: true,
        showPaginationSwitch: true,
        pageSize: 10,
        pageList: [10, 20, 30, 150, 250, 350, 500],
        search: true,
        showColumns: false,
        showRefresh: false,
        showExport: true,
        exportTypes: ['excel', 'xml', 'txt', 'pdf'],
        exportOptions: {
            "fileName": "Reporte Header Columnas",
            "worksheetName": "Prueba",
            "jspdf": {
                "autotable": {
                    "styles": { "rowHeight": 20, "fontSize": 12 },
                    "headerStyles": { "fillColor": 255, "textColor": 0 },
                    "alternateRowStyles": { "fillColor": [236, 240, 241], "textColor": 0 }
                }
            }
        },
        clickToSelect: true,
        columns: [
            [{
                field: 'empresa',
                colspan: 2,
                align: 'center',
                valign: 'middle',
                title: 'Empresa'
            }, {
                title: 'Fecha',
                field: 'fecha',
                colspan: 4,
                align: 'center',
                valign: 'middle',
            }]
            , [{
                field: 'id',
                title: 'Id',
                sortable: true
            }, {
                field: 'first_name',
                title: 'First Name',
                sortable: true
            }, {
                field: 'last_name',
                title: 'Last Name',
                sortable: true
            }, {
                field: 'email',
                title: 'Email',
                sortable: true
            }, {
                field: 'gender',
                title: 'Gender',
                sortable: true
            }, {
                field: 'ip_address',
                title: 'IP Address',
                sortable: true
            }]


        ]
    });
};

var init2 = function () {
    $('#table2').bootstrapTable({

        data: data,
        cache: false,
        height: 494,
        striped: false,
        pagination: true,
        sortable: true,
        locale: 'es-Ar',
        sortable: true,
        sortOrder: 'asc',
        showToggle: true,
        showPaginationSwitch: true,
        pageSize: 10,
        pageList: [10, 20, 30, 150, 250, 350, 500],
        search: true,
        showColumns: false,
        showRefresh: false,
        showExport: true,
        exportTypes: ['excel', 'xml', 'txt', 'pdf'],
        exportOptions: {
            "fileName": "Reporte Header Columnas",
            "worksheetName": "Prueba",
            "jspdf": {
                "autotable": {
                    "styles": { "rowHeight": 20, "fontSize": 12 },
                    "headerStyles": { "fillColor": 255, "textColor": 0 },
                    "alternateRowStyles": { "fillColor": [236, 240, 241], "textColor": 0 }
                }
            }
        },
        clickToSelect: true,
        columns: [
            [{
                colspan: 2,
                align: 'center',
                valign: 'middle',
                title: 'Empresa'
            }, {
                title: 'Fecha',
                colspan: 4,
                align: 'center',
                valign: 'middle',
            }],
            [{
                colspan: 2,
                align: 'center',
                valign: 'middle',
                title: 'Empresa 1'
            }, {
                title: 'Fecha: ' + new Date().toDateString(),
                colspan: 4,
                align: 'center',
                valign: 'middle',
            }]
            , [{
                field: 'id',
                title: 'Id',
                sortable: true
            }, {
                field: 'first_name',
                title: 'First Name',
                sortable: true
            }, {
                field: 'last_name',
                title: 'Last Name',
                sortable: true
            }, {
                field: 'email',
                title: 'Email',
                sortable: true
            }, {
                field: 'gender',
                title: 'Gender',
                sortable: true
            }, {
                field: 'ip_address',
                title: 'IP Address',
                sortable: true
            }]


        ]
    });
};

$(document).ready(function () {
    init();
    init2();
});